//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class COR_Forma_Fruta
    {
        public int FrutaID { get; set; }
        public int FormaID { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
    }
}
