//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrutaEntities : DbContext
    {
        public FrutaEntities()
            : base("name=FrutaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COR_Forma> COR_Forma { get; set; }
        public virtual DbSet<COR_Forma_Fruta> COR_Forma_Fruta { get; set; }
        public virtual DbSet<COR_Fruta> COR_Fruta { get; set; }
    }
}
